version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: ddtrace
    versions:
    - 0.46.0
    - 0.47.0
    - 0.48.0
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: isort
    versions:
    - 5.7.0
